In [17]:
# Import 需要的套件
import os
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [18]:
# 設定 data_path
dir_data = './data/ml100marathon/'
f_app_train = os.path.join(dir_data, 'train_data.csv')
f_app_test = os.path.join(dir_data, 'test_features.csv')
f_app_sample = os.path.join(dir_data, 'sample_submission.csv')

train = pd.read_csv(f_app_train)
test = pd.read_csv(f_app_test)
sample = pd.read_csv(f_app_sample)

In [19]:
test.head()

,name,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,...,loan_advances,long_term_incentive,other,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
0,BELDEN TIMOTHY N,5249999.0,2144013.0,-2334434.0,NaN,tim.belden@enron.com,953136.0,17355.0,484.0,228.0,...,NaN,NaN,210698.0,157569.0,NaN,213999.0,5521.0,7991.0,5501630.0,1110705.0
1,BOWEN JR RAYMOND M,1350000.0,NaN,-833.0,NaN,raymond.bowen@enron.com,NaN,65907.0,27.0,140.0,...,NaN,974293.0,1621.0,252055.0,NaN,278601.0,1593.0,1858.0,2669589.0,252055.0
2,HANNON KEVIN P,1500000.0,NaN,-3117011.0,NaN,kevin.hannon@enron.com,5538001.0,34039.0,32.0,32.0,...,NaN,1617011.0,11350.0,853064.0,NaN,243293.0,1035.0,1045.0,288682.0,6391065.0
3,DELAINEY DAVID W,3000000.0,NaN,NaN,NaN,david.delainey@enron.com,2291113.0,86174.0,3069.0,66.0,...,NaN,1294981.0,1661.0,1323148.0,NaN,365163.0,2097.0,3093.0,4747979.0,3614261.0
4,CAUSEY RICHARD A,1000000.0,NaN,-235000.0,NaN,richard.causey@enron.com,NaN,30674.0,49.0,58.0,...,NaN,350000.0,307895.0,2502063.0,NaN,415189.0,1585.0,1892.0,1868758.0,2502063.0

In [20]:
#填補遺失值
test['bonus'] = test['bonus'].fillna(test['bonus'].median())
test['deferral_payments'] = test['deferral_payments'].fillna(test['deferral_payments'].median())
test['deferred_income'] = test['deferred_income'].fillna(test['deferred_income'].median())
test['director_fees'] = test['director_fees'].fillna(test['director_fees'].median())
test['exercised_stock_options'] = test['exercised_stock_options'].fillna(test['exercised_stock_options'].median())
test['expenses'] = test['expenses'].fillna(test['expenses'].median())
test['from_messages'] = test['from_messages'].fillna(test['from_messages'].median())
test['from_poi_to_this_person'] = test['from_poi_to_this_person'].fillna(test['from_poi_to_this_person'].median())
test['from_this_person_to_poi'] = test['from_this_person_to_poi'].fillna(test['from_this_person_to_poi'].median())
test['loan_advances'] = test['loan_advances'].fillna(test['loan_advances'].median())
test['long_term_incentive'] = test['long_term_incentive'].fillna(test['long_term_incentive'].median())
test['other'] = test['other'].fillna(test['other'].median())
test['restricted_stock'] = test['restricted_stock'].fillna(test['restricted_stock'].median())
test['restricted_stock_deferred'] = test['restricted_stock_deferred'].fillna(test['restricted_stock_deferred'].median())
test['salary'] = test['salary'].fillna(test['salary'].median())
test['shared_receipt_with_poi'] = test['shared_receipt_with_poi'].fillna(test['shared_receipt_with_poi'].median())
test['to_messages'] = test['to_messages'].fillna(test['to_messages'].median())
test['total_payments'] = test['total_payments'].fillna(test['total_payments'].median())
test['total_stock_value'] = test['total_stock_value'].fillna(test['total_stock_value'].median())

#Total outliter
test.drop([20])

,name,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,...,loan_advances,long_term_incentive,other,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
0,BELDEN TIMOTHY N,5249999.0,2144013.0,-2334434.0,118324.0,tim.belden@enron.com,953136.0,17355.0,484.0,228.0,...,42962500.0,461912.0,210698.0,157569.0,-223782.5,213999.0,5521.0,7991.0,5501630.0,1110705.0
1,BOWEN JR RAYMOND M,1350000.0,564348.0,-833.0,118324.0,raymond.bowen@enron.com,2027865.0,65907.0,27.0,140.0,...,42962500.0,974293.0,1621.0,252055.0,-223782.5,278601.0,1593.0,1858.0,2669589.0,252055.0
2,HANNON KEVIN P,1500000.0,564348.0,-3117011.0,118324.0,kevin.hannon@enron.com,5538001.0,34039.0,32.0,32.0,...,42962500.0,1617011.0,11350.0,853064.0,-223782.5,243293.0,1035.0,1045.0,288682.0,6391065.0
3,DELAINEY DAVID W,3000000.0,564348.0,-235000.0,118324.0,david.delainey@enron.com,2291113.0,86174.0,3069.0,66.0,...,42962500.0,1294981.0,1661.0,1323148.0,-223782.5,365163.0,2097.0,3093.0,4747979.0,3614261.0
4,CAUSEY RICHARD A,1000000.0,564348.0,-235000.0,118324.0,richard.causey@enron.com,2027865.0,30674.0,49.0,58.0,...,42962500.0,350000.0,307895.0,2502063.0,-223782.5,415189.0,1585.0,1892.0,1868758.0,2502063.0
5,HICKERSON GARY J,1700000.0,564348.0,-235000.0,118324.0,gary.hickerson@enron.com,2027865.0,98849.0,27.0,40.0,...,42962500.0,69223.0,1936.0,441096.0,-223782.5,211788.0,900.0,1320.0,2081796.0,441096.0
6,FREVERT MARK A,2000000.0,6426990.0,-3367011.0,118324.0,mark.frevert@enron.com,10433518.0,86987.0,21.0,242.0,...,2000000.0,1617011.0,7427621.0,4188667.0,-223782.5,1060932.0,2979.0,3275.0,17252530.0,14622185.0
7,CHAN RONNIE,1000000.0,564348.0,-98784.0,98784.0,NaN,2027865.0,61817.0,29.0,40.0,...,42962500.0,461912.0,74607.0,32460.0,-32460.0,272847.0,1074.0,1607.0,1061827.0,1838142.0
8,DONAHUE JR JEFFREY M,800000.0,564348.0,-300000.0,118324.0,jeff.donahue@enron.com,765920.0,96268.0,22.0,188.0,...,42962500.0,461912.0,891.0,315068.0,-223782.5,278601.0,772.0,865.0,875760.0,1080988.0
9,REYNOLDS LAWRENCE,100000.0,51365.0,-200000.0,118324.0,NaN,4160672.0,8409.0,29.0,40.0,...,42962500.0,156250.0,202052.0,201483.0,-140264.0,76399.0,1074.0,1607.0,394475.0,4221891.0
10,HORTON STANLEY C,1000000.0,3131860.0,-235000.0,118324.0,stanley.horton@enron.com,5210569.0,61817.0,1073.0,44.0,...,42962500.0,461912.0,74607.0,2046079.0,-223782.5,272847.0,1074.0,2350.0,3131860.0,7256648.0
11,LEWIS RICHARD,1000000.0,564348.0,-235000.0,118324.0,richard.lewis@enron.com,850477.0,61817.0,26.0,10.0,...,42962500.0,461912.0,74607.0,423547.5,-223782.5,272847.0,739.0,952.0,1061827.0,850477.0
12,SHERRICK JEFFREY B,1000000.0,564348.0,-235000.0,118324.0,jeffrey.sherrick@enron.com,1426469.0,61817.0,25.0,39.0,...,42962500.0,461912.0,74607.0,405999.0,-223782.5,272847.0,583.0,613.0,1061827.0,1832468.0
13,MEYER JEROME J,1000000.0,564348.0,-38346.0,38346.0,NaN,2027865.0,2151.0,29.0,40.0,...,42962500.0,461912.0,74607.0,423547.5,-223782.5,272847.0,1074.0,1607.0,2151.0,1838142.0
14,DERRICK JR. JAMES V,800000.0,564348.0,-1284000.0,118324.0,james.derrick@enron.com,8831913.0,51124.0,909.0,64.0,...,42962500.0,484000.0,7482.0,1787380.0,-1787380.0,492375.0,1401.0,2181.0,550981.0,8831913.0
15,PIRO JIM,1000000.0,564348.0,-235000.0,118324.0,jim.piro@enron.com,2027865.0,61817.0,16.0,0.0,...,42962500.0,461912.0,74607.0,47304.0,-223782.5,272847.0,3.0,58.0,1061827.0,47304.0
16,DETMERING TIMOTHY J,425000.0,875307.0,-775241.0,118324.0,timothy.detmering@enron.com,2027865.0,52255.0,29.0,40.0,...,42962500.0,415657.0,1105.0,315068.0,-315068.0,210500.0,1074.0,1607.0,1204583.0,2027865.0
17,KISHKILL JOSEPH G,1000000.0,564348.0,-51042.0,118324.0,joe.kishkill@enron.com,2027865.0,116335.0,29.0,40.0,...,42962500.0,461912.0,465357.0,1034346.0,-223782.5,174246.0,1074.0,1607.0,704896.0,1034346.0
18,BAY FRANKLIN R,400000.0,260455.0,-201641.0,118324.0,frank.bay@enron.com,2027865.0,129142.0,29.0,40.0,...,42962500.0,461912.0,69.0,145796.0,-82782.0,239671.0,1074.0,1607.0,827696.0,63014.0
19,PRENTICE JAMES,1000000.0,564348.0,-235000.0,118324.0,james.prentice@enron.com,886231.0,61817.0,29.0,40.0,...,42962500.0,461912.0,74607.0,208809.0,-223782.5,272847.0,1074.0,1607.0,564348.0,1095040.0
21,FALLON JAMES B,2500000.0,564348.0,-235000.0,118324.0,jim.fallon@enron.com,940257.0,95924.0,75.0,42.0,...,42962500.0,374347.0,401481.0,1392142.0,-223782.5,304588.0,1604.0,1755.0,3676340.0,2332399.0
22,METTS MARK,600000.0,564348.0,-235000.0,118324.0,mark.metts@enron.com,2027865.0,94299.0,29.0,38.0,...,42962500.0,461912.0,1740.0,585062.0,-223782.5,365788.0,702.0,807.0,1061827.0,585062.0
23,WODRASKA JOHN,1000000.0,564348.0,-235000.0,118324.0,john.wodraska@enron.com,2027865.0,61817.0,29.0,40.0,...,42962500.0,461912.0,189583.0,423547.5,-223782.5,272847.0,1074.0,1607.0,189583.0,1838142.0
24,MORDAUNT KRISTINA M,325000.0,564348.0,-235000.0,118324.0,kristina.mordaunt@enron.com,2027865.0,35018.0,29.0,40.0,...,42962500.0,461912.0,1411.0,208510.0,-223782.5,267093.0,1074.0,1607.0,628522.0,208510.0
25,CARTER REBECCA C,300000.0,564348.0,-159792.0,118324.0,rebecca.carter@enron.com,2027865.0,61817.0,15.0,29.0,...,42962500.0,75000.0,540.0,307301.0,-307301.0,261809.0,196.0,312.0,477557.0,1838142.0
26,BHATNAGAR SANJAY,1000000.0,564348.0,-235000.0,137864.0,sanjay.bhatnagar@enron.com,2604490.0,61817.0,29.0,0.0,...,42962500.0,461912.0,137864.0,-2604490.0,15456290.0,272847.0,463.0,523.0,15456290.0,1838142.0
27,WALTERS GARETH W,1000000.0,53625.0,-235000.0,118324.0,NaN,1030329.0,33785.0,29.0,40.0,...,42962500.0,461912.0,74607.0,423547.5,-223782.5,272847.0,1074.0,1607.0,87410.0,1030329.0
28,BIBI PHILIPPE A,1000000.0,564348.0,-235000.0,118324.0,philippe.bibi@enron.com,1465734.0,38559.0,40.0,23.0,...,42962500.0,369721.0,425688.0,378082.0,-223782.5,213625.0,1336.0,1607.0,2047593.0,1843816.0
29,SHERRIFF JOHN R,1500000.0,564348.0,-235000.0,118324.0,john.sherriff@enron.com,1835558.0,61817.0,92.0,28.0,...,42962500.0,554422.0,1852186.0,1293424.0,-223782.5,428780.0,2103.0,3187.0,4335388.0,3128982.0
30,GIBBS DANA R,1000000.0,504610.0,-235000.0,118324.0,dana.gibbs@enron.com,2218275.0,61817.0,12.0,0.0,...,42962500.0,461912.0,74607.0,423547.5,-223782.5,272847.0,23.0,169.0,966522.0,2218275.0
31,LINDHOLM TOD A,200000.0,204075.0,-235000.0,118324.0,tod.lindholm@enron.com,2549361.0,57727.0,29.0,40.0,...,42962500.0,175000.0,2630.0,514847.0,-223782.5,236457.0,1074.0,1607.0,875889.0,3064208.0
32,MCMAHON JEFFREY,2600000.0,564348.0,-235000.0,118324.0,jeffrey.mcmahon@enron.com,1104054.0,137108.0,48.0,58.0,...,42962500.0,694862.0,297353.0,558801.0,-223782.5,370448.0,2228.0,2355.0,4099771.0,1662855.0

In [33]:
from sklearn.preprocessing import MinMaxScaler, Imputer
# Scale each feature to 0-1
scaler = MinMaxScaler(feature_range = (0, 1))


# Repeat with the scaler
scaler.fit(test['bonus','deferral_payments','deferred_income','director_fees','exercised_stock_options','expenses','from_messages','from_poi_to_this_person','from_this_person_to_poi','loan_advances','long_term_incentive','other','restricted_stock','restricted_stock_deferred','salary','shared_receipt_with_poi','to_messages','total_payments','total_stock_value'])
test = scaler.transform(test['bonus','deferral_payments','deferred_income','director_fees','exercised_stock_options','expenses','from_messages','from_poi_to_this_person','from_this_person_to_poi','loan_advances','long_term_incentive','other','restricted_stock','restricted_stock_deferred','salary','shared_receipt_with_poi','to_messages','total_payments','total_stock_value'])

KeyError: ('bonus', 'deferral_payments', 'deferred_income', 'director_fees', 'exercised_stock_options', 'expenses', 'from_messages', 'from_poi_to_this_person', 'from_this_person_to_poi', 'loan_advances', 'long_term_incentive', 'other', 'restricted_stock', 'restricted_stock_deferred', 'salary', 'shared_receipt_with_poi', 'to_messages', 'total_payments', 'total_stock_value')